### ISSUE TITLE
enhancement: 슬랙 잡답방에서 테코브러리 주소를 알려주는 기능

### ISSUE THREAD

**Issue by MrKwon** [milzipmoza-developers/tecobrary-noti-slackbot#2]
도메인 주소가 어려워서 유저들이 이용하는데 어려움이 있다.

테코비스가 어떤 커맨드를 탐지하면 도메인 주소를 알려주는 기능과 홈 화면에 추가하기를 하면 더 쉽게 사용할 수 있다는 점을 알려주는(홈 화면에 추가하는 방법은 iOS, Android 각각 알려주는 문서 링크) 메시지를 보낼 수 있도록 변경한다.

**Comment by workromancer** [comment]
2019.11.07 13:23 배포 완료 및 정상 동작 확인
